import { Grid } from '@mui/material'
import Head from 'next/head'
import React from 'react'

interface LayoutProps{
  title: string
  children: any
  Wrap: string
}

export const Layout = ({children,title,Wrap}:LayoutProps) => {

  const sxOptionsGridLayout = {
    width:'100%',
    height:'100vh',
    flexWrap: Wrap,
  }


  return (
    <>
      <Head>
          <title>{`MyChat | ${title}`}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid sx={sxOptionsGridLayout}>
        {children}
      </Grid>
    </>
  )
}
